# Generated by Django 3.2.5 on 2023-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addkart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cemail', models.CharField(max_length=30)),
                ('cnam', models.CharField(max_length=30)),
                ('cpho', models.BigIntegerField()),
                ('cpid', models.BigIntegerField()),
                ('cpname', models.CharField(max_length=30)),
                ('cpimg', models.FileField(blank=True, max_length=300, null=True, upload_to='media')),
                ('cprice', models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=100)),
                ('corderdate', models.CharField(blank=True, max_length=30, null=True)),
                ('cordercout', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'addkart',
            },
        ),
        migrations.CreateModel(
            name='formreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone', models.BigIntegerField()),
                ('User_type', models.BigIntegerField(null=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'formreg',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tittle', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=30)),
                ('circlesale', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, max_length=300, null=True, upload_to='media')),
                ('rate', models.BigIntegerField()),
                ('cutrate', models.BigIntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
