# Generated by Django 3.2.5 on 2023-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addkart',
            name='ctotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=100),
        ),
    ]
